language: node_js
node_js:
  - "10"
cache:
  yarn: true
branches:
  only:
    - master
before_script:
  - yarn lerna bootstrap
  - yarn lint
script:
  - yarn build
after_script:
# Tests run after building because of the project being a monorepo
  - yarn test --coverage
  - yarn type-check
  - codecov -f coverage/*.json
